services:
  - type: web
    name: blue-horizon-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn blue_horizon.app.api:app --host 0.0.0.0 --port $PORT --loop asyncio
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /health 